#!/usr/bin/env python3
"""Generate gnome_typer/keycodes.py from the kernel's input-event-codes.h.

Committed output means the daemon never needs kernel headers at runtime.
"""
import pathlib
import re
import sys

HEADER = "/usr/include/linux/input-event-codes.h"
OUT = pathlib.Path(__file__).resolve().parent.parent / "daemon" / "gnome_typer" / "keycodes.py"

def main():
    src = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else HEADER)
    if not src.exists():
        sys.exit(f"missing {src}; install linux-libc-dev")

    literal = re.compile(r"^#define\s+((?:KEY|BTN)_\w+)\s+(0x[0-9a-fA-F]+|\d+)\s*$")
    alias = re.compile(r"^#define\s+((?:KEY|BTN)_\w+)\s+((?:KEY|BTN)_\w+)\s*$")

    codes, aliases = {}, {}
    for line in src.read_text().splitlines():
        if m := literal.match(line.strip()):
            name, value = m.group(1), m.group(2)
            codes[name] = int(value, 16) if value.startswith("0x") else int(value)
        elif m := alias.match(line.strip()):
            aliases[m.group(1)] = m.group(2)

    for name, target in aliases.items():
        if target in codes:
            codes.setdefault(name, codes[target])

    # code -> canonical name: prefer the shortest, then alphabetical, for stability.
    canonical = {}
    for name, code in sorted(codes.items(), key=lambda kv: (len(kv[0]), kv[0])):
        canonical.setdefault(code, name)

    lines = [
        '"""Linux input event codes. Generated by tools/gen_keycodes.py - do not edit."""',
        "",
        "NAME_TO_CODE = {",
    ]
    lines += [f"    {name!r}: {code}," for name, code in sorted(codes.items())]
    lines += ["}", "", "CODE_TO_NAME = {"]
    lines += [f"    {code}: {name!r}," for code, name in sorted(canonical.items())]
    lines += [
        "}",
        "",
        "",
        "def resolve(name):",
        '    """Accept \'KEY_A\', \'a\', or a raw integer code; return an int code or None."""',
        "    if isinstance(name, int):",
        "        return name",
        "    text = str(name).strip()",
        "    if text.isdigit():",
        "        return int(text)",
        "    upper = text.upper()",
        "    for candidate in (upper, f'KEY_{upper}', f'BTN_{upper}'):",
        "        if candidate in NAME_TO_CODE:",
        "            return NAME_TO_CODE[candidate]",
        "    return None",
        "",
    ]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))
    print(f"wrote {OUT} ({len(codes)} names, {len(canonical)} codes)")

if __name__ == "__main__":
    main()
